### ISSUE TITLE
HELLO

### ISSUE THREAD

**Issue by milanesoelgato** [evox-penang/android_device_motorola_penang#1]
I would like to know what the installation method is, I would like to try it on a moto g53 5G (GLOBAL VERSION)

**Comment by nattolecats** [comment]
Hi. Install method is following steps:

1. flash boot.img, vendor_boot.img, dtbo.img
2. reboot to recovery
3. `adb sideload copy-partitions.zip` (**DO NOT** forget this, may lead to brick)
4. reboot to recovery
5. format data
6. `adb sideload evolution_penang-ota-*.zip` (or `fastboot update *.zip`) 
7. reboot to system

btw this tree optimized for Japan edition, so may not work properly all functions though.

**Comment by milanesoelgato** [comment]
Could you send me copy-partitions.zip. please?

**Comment by nattolecats** [comment]
Sure. This is the copy partitions that worked on penang.
Good luck!

[copy-partitions-20210323_1922.zip](https://github.com/evox-penang/android_device_motorola_penang/files/14000051/copy-partitions-20210323_1922.zip)

**Comment by milanesoelgato** [comment]
I got it to start, I'll see if I receive messages and calls, if it identifies me that I have two SIMs

**Comment by milanesoelgato** [comment]
If it worked, it recognizes the 5g and the messages, I didn't expect it, it was a surprise for me, congratulations for your great work
